# Generated by Django 5.1.5 on 2025-02-03 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paths',
            name='dest_url',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='paths',
            name='src_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
