# Generated by Django 5.1.5 on 2025-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_paths_dest_url_alter_paths_src_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='paths',
            name='admin_added',
            field=models.BooleanField(default=False),
        ),
    ]
