# Generated by Django 5.1.5 on 2025-02-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paths_admin_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paths',
            old_name='src_path',
            new_name='short_code',
        ),
    ]
