# Generated by Django 5.1.5 on 2025-02-06 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_src_path_paths_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paths',
            name='dest_url',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
