# Generated by Django 5.1.5 on 2025-02-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('main', '0006_paths_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paths',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pathsapikey'),
        ),
    ]
